name: Build and Package Jefo App on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: jefo
    runs-on: windows-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Python 3.10
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies (Torch, OpenCV, Pillow, Tkinter, etc.)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu
          pip install opencv-python pillow requests numpy matplotlib

      # Install Tkinter for Windows
      - name: Install Tkinter
        run: |
          python -m pip install tk

      # Create a directory to store dependencies
      - name: Create Dist Directory
        run: |
          mkdir dist

      # Freeze dependencies into requirements.txt
      - name: Freeze Requirements
        run: |
          pip freeze > requirements.txt

      # Copy all project files to the dist folder, excluding the dist folder itself
      - name: Copy Project Files
        run: |
          robocopy . dist /MIR /XD dist

      # Zip the project folder including all dependencies and files
      - name: Zip Project
        run: |
          powershell Compress-Archive -Path dist/* -DestinationPath jefo_app.zip

      # Upload the artifact (zipped project)
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jefo-app
          path: jefo_app.zip
