name: Build and Run Jefo App on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: jefo
    runs-on: windows-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies (Torch, OpenCV, Pillow, tkinter, etc.)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu
          pip install opencv-python pillow requests numpy matplotlib

      # Install Tkinter for Windows
      - name: Install Tkinter
        run: |
          python -m pip install tk

      # Run the application (Optional: You can replace this with your main script)
      - name: Run Jefo App
        run: |
          python jefo.py  # Replace with your entry-point script (e.g., jefo_app.py or captcha_solver.py)

      # Run tests (Optional: if you have unit tests)
      - name: Run Tests
        run: |
          pytest tests/  # Replace with the path to your test directory if any
